[theme]
base = "dark"
primaryColor = "#7C3AED"
backgroundColor = "#0E111B"
secondaryBackgroundColor = "#191D2E"
textColor = "#F1F5F9"
font = "sans serif"
[server]
maxUploadSize = 25
[browser]
gatherUsageStats = false
